set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

get_filename_component(CERBERUS_FRAMEWORK_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

find_program(CERBERUS_REMOTE_C_COMPILER_GENERIC NAMES aarch64-linux-gnu-gcc REQUIRED)
find_program(CERBERUS_REMOTE_CXX_COMPILER_GENERIC NAMES aarch64-linux-gnu-g++ REQUIRED)

if(DEFINED ENV{CERBERUS_REMOTE_SSH_TARGET} AND NOT "$ENV{CERBERUS_REMOTE_SSH_TARGET}" STREQUAL "")
  set(CERBERUS_REMOTE_SSH_TARGET "$ENV{CERBERUS_REMOTE_SSH_TARGET}" CACHE STRING "SSH target used to refresh the remote sysroot, for example pi@target-host" FORCE)
else()
  set(CERBERUS_REMOTE_SSH_TARGET "" CACHE STRING "SSH target used to refresh the remote sysroot, for example pi@target-host")
endif()

if(DEFINED ENV{CERBERUS_REMOTE_EXTRA_SYNC_PATHS} AND NOT "$ENV{CERBERUS_REMOTE_EXTRA_SYNC_PATHS}" STREQUAL "")
  set(CERBERUS_REMOTE_EXTRA_SYNC_PATHS "$ENV{CERBERUS_REMOTE_EXTRA_SYNC_PATHS}" CACHE STRING "Semicolon-separated extra remote paths to synchronize into the remote sysroot" FORCE)
else()
  set(CERBERUS_REMOTE_EXTRA_SYNC_PATHS "" CACHE STRING "Semicolon-separated extra remote paths to synchronize into the remote sysroot")
endif()

set(CERBERUS_SYNC_REMOTE_SYSROOT OFF CACHE BOOL "Synchronize the configured remote sysroot via SSH during configure")
set(CERBERUS_SYSROOT_DIR "${CERBERUS_FRAMEWORK_ROOT}/sysroot" CACHE PATH "Path to the local ARM64 sysroot")

set(CERBERUS_HAS_POPULATED_SYSROOT FALSE)
if(EXISTS "${CERBERUS_SYSROOT_DIR}/usr")
  set(CERBERUS_HAS_POPULATED_SYSROOT TRUE)
endif()

set(CERBERUS_SHOULD_SYNC_SYSROOT FALSE)
if(CERBERUS_SYNC_REMOTE_SYSROOT)
  set(CERBERUS_SHOULD_SYNC_SYSROOT TRUE)
elseif(NOT CERBERUS_HAS_POPULATED_SYSROOT AND NOT CERBERUS_REMOTE_SSH_TARGET STREQUAL "")
  # Bootstrap a missing sysroot even when auto-refresh is disabled.
  set(CERBERUS_SHOULD_SYNC_SYSROOT TRUE)
endif()

if(CERBERUS_SHOULD_SYNC_SYSROOT)
  if(CERBERUS_REMOTE_SSH_TARGET STREQUAL "")
    if(CERBERUS_HAS_POPULATED_SYSROOT)
      message(WARNING "CERBERUS_SYNC_REMOTE_SYSROOT is ON but CERBERUS_REMOTE_SSH_TARGET is empty. Reusing the existing sysroot at ${CERBERUS_SYSROOT_DIR}.")
    else()
      message(FATAL_ERROR "No populated sysroot exists at ${CERBERUS_SYSROOT_DIR}, and CERBERUS_REMOTE_SSH_TARGET is empty.")
    endif()
  else()
    set(CERBERUS_SYNC_SCRIPT "${CERBERUS_FRAMEWORK_ROOT}/scripts/sync_remote_sysroot.sh")
    if(NOT EXISTS "${CERBERUS_SYNC_SCRIPT}")
      message(FATAL_ERROR "Remote sysroot sync script not found: ${CERBERUS_SYNC_SCRIPT}")
    endif()

    find_program(CERBERUS_BASH_EXECUTABLE bash REQUIRED)

    set(CERBERUS_SYNC_COMMAND
      "${CERBERUS_BASH_EXECUTABLE}"
      "${CERBERUS_SYNC_SCRIPT}"
      "${CERBERUS_REMOTE_SSH_TARGET}"
      "${CERBERUS_SYSROOT_DIR}"
    )
    foreach(CERBERUS_EXTRA_PATH IN LISTS CERBERUS_REMOTE_EXTRA_SYNC_PATHS)
      if(NOT CERBERUS_EXTRA_PATH STREQUAL "")
        list(APPEND CERBERUS_SYNC_COMMAND "${CERBERUS_EXTRA_PATH}")
      endif()
    endforeach()

    execute_process(
      COMMAND ${CERBERUS_SYNC_COMMAND}
      WORKING_DIRECTORY "${CERBERUS_FRAMEWORK_ROOT}"
      RESULT_VARIABLE CERBERUS_SYNC_RESULT
      OUTPUT_VARIABLE CERBERUS_SYNC_STDOUT
      ERROR_VARIABLE CERBERUS_SYNC_STDERR
    )

    if(NOT CERBERUS_SYNC_RESULT EQUAL 0)
      message(FATAL_ERROR
        "Failed to synchronize the remote sysroot from ${CERBERUS_REMOTE_SSH_TARGET} into ${CERBERUS_SYSROOT_DIR}.\n"
        "stdout:\n${CERBERUS_SYNC_STDOUT}\n"
        "stderr:\n${CERBERUS_SYNC_STDERR}"
      )
    endif()

    set(CERBERUS_HAS_POPULATED_SYSROOT TRUE)
    if(CERBERUS_SYNC_REMOTE_SYSROOT)
      message(STATUS "Synchronized remote sysroot into ${CERBERUS_SYSROOT_DIR}")
    else()
      message(STATUS "Bootstrapped remote sysroot into ${CERBERUS_SYSROOT_DIR}")
    endif()
  endif()
endif()

if(NOT CERBERUS_HAS_POPULATED_SYSROOT)
  set(CERBERUS_REMOTE_TOOLCHAIN_READY OFF CACHE INTERNAL "Whether the remote ARM64 toolchain has a populated sysroot available" FORCE)
  set(CMAKE_C_COMPILER "${CERBERUS_REMOTE_C_COMPILER_GENERIC}" CACHE FILEPATH "C compiler for remote ARM64 builds" FORCE)
  set(CMAKE_CXX_COMPILER "${CERBERUS_REMOTE_CXX_COMPILER_GENERIC}" CACHE FILEPATH "CXX compiler for remote ARM64 builds" FORCE)
  set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu)
  set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu)
  message(STATUS
    "CERBERUS_SYSROOT_DIR does not look like a populated sysroot yet: ${CERBERUS_SYSROOT_DIR}\n"
    "Configure will continue in bootstrap mode. Set CERBERUS_REMOTE_SSH_TARGET and reconfigure, or populate CERBERUS_SYSROOT_DIR manually."
  )
  return()
endif()

set(CERBERUS_REMOTE_C_COMPILER "${CERBERUS_REMOTE_C_COMPILER_GENERIC}")
set(CERBERUS_REMOTE_CXX_COMPILER "${CERBERUS_REMOTE_CXX_COMPILER_GENERIC}")

set(CERBERUS_TARGET_LIBSTDCXX_VERSION "")
file(GLOB CERBERUS_TARGET_LIBSTDCXX_DIRS LIST_DIRECTORIES TRUE "${CERBERUS_SYSROOT_DIR}/usr/include/c++/*")
foreach(CERBERUS_TARGET_LIBSTDCXX_DIR IN LISTS CERBERUS_TARGET_LIBSTDCXX_DIRS)
  if(IS_DIRECTORY "${CERBERUS_TARGET_LIBSTDCXX_DIR}")
    get_filename_component(CERBERUS_TARGET_LIBSTDCXX_CANDIDATE "${CERBERUS_TARGET_LIBSTDCXX_DIR}" NAME)
    if(CERBERUS_TARGET_LIBSTDCXX_CANDIDATE MATCHES "^[0-9]+$")
      set(CERBERUS_TARGET_LIBSTDCXX_VERSION "${CERBERUS_TARGET_LIBSTDCXX_CANDIDATE}")
      break()
    endif()
  endif()
endforeach()

if(NOT CERBERUS_TARGET_LIBSTDCXX_VERSION STREQUAL "")
  find_program(CERBERUS_REMOTE_C_COMPILER_VERSIONED NAMES "aarch64-linux-gnu-gcc-${CERBERUS_TARGET_LIBSTDCXX_VERSION}")
  find_program(CERBERUS_REMOTE_CXX_COMPILER_VERSIONED NAMES "aarch64-linux-gnu-g++-${CERBERUS_TARGET_LIBSTDCXX_VERSION}")

  if(CERBERUS_REMOTE_C_COMPILER_VERSIONED AND CERBERUS_REMOTE_CXX_COMPILER_VERSIONED)
    set(CERBERUS_REMOTE_C_COMPILER "${CERBERUS_REMOTE_C_COMPILER_VERSIONED}")
    set(CERBERUS_REMOTE_CXX_COMPILER "${CERBERUS_REMOTE_CXX_COMPILER_VERSIONED}")
  else()
    execute_process(
      COMMAND "${CERBERUS_REMOTE_CXX_COMPILER_GENERIC}" -dumpfullversion
      OUTPUT_VARIABLE CERBERUS_REMOTE_CXX_COMPILER_VERSION
      OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    string(REGEX MATCH "^[0-9]+" CERBERUS_REMOTE_CXX_COMPILER_MAJOR "${CERBERUS_REMOTE_CXX_COMPILER_VERSION}")

    if(NOT CERBERUS_REMOTE_CXX_COMPILER_MAJOR STREQUAL "${CERBERUS_TARGET_LIBSTDCXX_VERSION}")
      message(FATAL_ERROR
        "The synced sysroot provides libstdc++ headers for GCC ${CERBERUS_TARGET_LIBSTDCXX_VERSION}, "
        "but the available host cross compiler is GCC ${CERBERUS_REMOTE_CXX_COMPILER_VERSION} at ${CERBERUS_REMOTE_CXX_COMPILER_GENERIC}.\n"
        "Install gcc-${CERBERUS_TARGET_LIBSTDCXX_VERSION}-aarch64-linux-gnu and g++-${CERBERUS_TARGET_LIBSTDCXX_VERSION}-aarch64-linux-gnu, "
        "then reconfigure."
      )
    endif()
  endif()
endif()

set(CERBERUS_REMOTE_TOOLCHAIN_READY ON CACHE INTERNAL "Whether the remote ARM64 toolchain has a populated sysroot available" FORCE)
set(CMAKE_C_COMPILER "${CERBERUS_REMOTE_C_COMPILER}" CACHE FILEPATH "C compiler for remote ARM64 builds" FORCE)
set(CMAKE_CXX_COMPILER "${CERBERUS_REMOTE_CXX_COMPILER}" CACHE FILEPATH "CXX compiler for remote ARM64 builds" FORCE)
set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu)
set(CMAKE_SYSROOT "${CERBERUS_SYSROOT_DIR}")

execute_process(
  COMMAND "${CERBERUS_REMOTE_C_COMPILER}" -print-file-name=include
  OUTPUT_VARIABLE CERBERUS_GCC_INTERNAL_INCLUDE_DIR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

if(CERBERUS_TARGET_LIBSTDCXX_VERSION STREQUAL "")
  execute_process(
    COMMAND "${CERBERUS_REMOTE_CXX_COMPILER}" -dumpfullversion
    OUTPUT_VARIABLE CERBERUS_REMOTE_CXX_COMPILER_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  string(REGEX MATCH "^[0-9]+" CERBERUS_TARGET_LIBSTDCXX_VERSION "${CERBERUS_REMOTE_CXX_COMPILER_VERSION}")
endif()

set(CERBERUS_SYSROOT_CXX_INCLUDE_CANDIDATES
  "${CMAKE_SYSROOT}/usr/include/c++/${CERBERUS_TARGET_LIBSTDCXX_VERSION}"
  "${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu/c++/${CERBERUS_TARGET_LIBSTDCXX_VERSION}"
  "${CMAKE_SYSROOT}/usr/include/c++/${CERBERUS_TARGET_LIBSTDCXX_VERSION}/backward"
)

set(CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS "")
foreach(CERBERUS_CXX_INCLUDE_DIR IN LISTS CERBERUS_SYSROOT_CXX_INCLUDE_CANDIDATES)
  if(EXISTS "${CERBERUS_CXX_INCLUDE_DIR}")
    list(APPEND CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS "${CERBERUS_CXX_INCLUDE_DIR}")
  endif()
endforeach()

if(NOT CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS)
  message(FATAL_ERROR
    "The sysroot at ${CMAKE_SYSROOT} does not provide libstdc++ headers for GCC ${CERBERUS_TARGET_LIBSTDCXX_VERSION}."
  )
endif()

set(CERBERUS_EFFECTIVE_C_INCLUDE_DIRS "")

if(IS_DIRECTORY "${CERBERUS_GCC_INTERNAL_INCLUDE_DIR}")
  list(APPEND CERBERUS_EFFECTIVE_C_INCLUDE_DIRS "${CERBERUS_GCC_INTERNAL_INCLUDE_DIR}")
endif()

set(CERBERUS_LINUX_UAPI_DIR "")
if(IS_DIRECTORY "${CMAKE_SYSROOT}/usr/lib/linux/uapi/arm64")
  set(CERBERUS_LINUX_UAPI_DIR "${CMAKE_SYSROOT}/usr/lib/linux/uapi/arm64")
elseif(IS_DIRECTORY "/usr/lib/linux/uapi/arm64")
  set(CERBERUS_LINUX_UAPI_DIR "/usr/lib/linux/uapi/arm64")
endif()

if(NOT CERBERUS_LINUX_UAPI_DIR STREQUAL "")
  list(APPEND CERBERUS_EFFECTIVE_C_INCLUDE_DIRS "${CERBERUS_LINUX_UAPI_DIR}")
endif()

set(CERBERUS_SYSROOT_C_INCLUDE_CANDIDATES
  "${CMAKE_SYSROOT}/usr/local/include"
  "${CMAKE_SYSROOT}/usr/include/aarch64-linux-gnu"
  "${CMAKE_SYSROOT}/usr/include"
)
foreach(CERBERUS_C_INCLUDE_DIR IN LISTS CERBERUS_SYSROOT_C_INCLUDE_CANDIDATES)
  if(EXISTS "${CERBERUS_C_INCLUDE_DIR}")
    list(APPEND CERBERUS_EFFECTIVE_C_INCLUDE_DIRS "${CERBERUS_C_INCLUDE_DIR}")
  endif()
endforeach()

list(APPEND CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS ${CERBERUS_EFFECTIVE_C_INCLUDE_DIRS})

set(CERBERUS_C_INCLUDE_FLAGS "-nostdinc")
foreach(CERBERUS_INCLUDE_DIR IN LISTS CERBERUS_EFFECTIVE_C_INCLUDE_DIRS)
  string(APPEND CERBERUS_C_INCLUDE_FLAGS " -isystem ${CERBERUS_INCLUDE_DIR}")
endforeach()

set(CERBERUS_CXX_INCLUDE_FLAGS "-nostdinc -nostdinc++")
foreach(CERBERUS_INCLUDE_DIR IN LISTS CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS)
  string(APPEND CERBERUS_CXX_INCLUDE_FLAGS " -isystem ${CERBERUS_INCLUDE_DIR}")
endforeach()

set(CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES "${CERBERUS_EFFECTIVE_C_INCLUDE_DIRS}" CACHE STRING "Implicit C include directories for the remote ARM64 toolchain" FORCE)
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "${CERBERUS_EFFECTIVE_CXX_INCLUDE_DIRS}" CACHE STRING "Implicit CXX include directories for the remote ARM64 toolchain" FORCE)

set(CERBERUS_REMOTE_PREFIX_PATHS
  "${CMAKE_SYSROOT}/usr"
  "${CMAKE_SYSROOT}/usr/local"
  "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/cmake"
)

set(CERBERUS_EFFECTIVE_PREFIX_PATHS "")
foreach(CERBERUS_PREFIX_PATH IN LISTS CERBERUS_REMOTE_PREFIX_PATHS)
  if(EXISTS "${CERBERUS_PREFIX_PATH}")
    list(APPEND CERBERUS_EFFECTIVE_PREFIX_PATHS "${CERBERUS_PREFIX_PATH}")
  endif()
endforeach()

if(CERBERUS_EFFECTIVE_PREFIX_PATHS)
  set(CMAKE_PREFIX_PATH "${CERBERUS_EFFECTIVE_PREFIX_PATHS}" CACHE STRING "Remote ARM64 package prefixes" FORCE)
endif()

file(GLOB CERBERUS_BOOST_CONFIG_DIRS LIST_DIRECTORIES TRUE "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/cmake/Boost-*")
list(SORT CERBERUS_BOOST_CONFIG_DIRS COMPARE NATURAL ORDER DESCENDING)
if(CERBERUS_BOOST_CONFIG_DIRS)
  list(GET CERBERUS_BOOST_CONFIG_DIRS 0 CERBERUS_BOOST_CONFIG_DIR)
  set(Boost_DIR "${CERBERUS_BOOST_CONFIG_DIR}" CACHE PATH "Boost config directory inside the remote ARM64 sysroot" FORCE)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS "--sysroot=${CMAKE_SYSROOT} ${CERBERUS_C_INCLUDE_FLAGS}" CACHE STRING "C flags for the remote ARM64 toolchain" FORCE)
set(CMAKE_CXX_FLAGS "--sysroot=${CMAKE_SYSROOT} ${CERBERUS_CXX_INCLUDE_FLAGS}" CACHE STRING "CXX flags for the remote ARM64 toolchain" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
  "${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig"
)
